lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    api_platform:
        check_path: /api/login_check
        username_path: email
        password_path: password
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: true
            name: Bearer
    set_cookies:
        Bearer: ~
    blocklist_token:
        enabled: true
        cache: cache.app
    remove_token_from_body_when_cookies_used: false

when@test:
    lexik_jwt_authentication:
        secret_key: '%kernel.project_dir%/config/jwt/private-test.pem'
        public_key: '%kernel.project_dir%/config/jwt/public-test.pem'
        pass_phrase: 'pass'
